### ISSUE TITLE
Feature request: weights in density.psp() function

### ISSUE THREAD

**Issue by idblr** [spatstat/spatstat.core#1]
Hi Spatstat Team,

I am interested in converting a line segment pattern `psp` of various types into a spatial density and I see that the `weights` argument is available for the `pixellate.psp()` function but not the `density.psp()` function. Would it be possible to add this feature?

Potential scenario: a (rough) simulation of air pollution transport from roadways of varying amounts (e.g., highways with more pollution that may travel farther from the roadway than surface streets). Currently, `density.psp()` can (roughly) achieve the varying level of transport with the `sigma` argument, but without the `weights` argument, the function assumes the line segments are of equal weight.

Here's a reproducible example:

Freeways
```
set.seed(1234)
L1 <- spatstat.geom::psp(runif(5),runif(5),runif(5),runif(5), window=spatstat.geom::owin())
D1 <- spatstat.core::density.psp(L1, sigma = 0.06)
plot(D1, main = "density(L1)")
plot(L1, add = TRUE, lty = 1)
```
![download](https://user-images.githubusercontent.com/10702814/109396607-65370e80-7900-11eb-9f5b-2dafc2365021.png)

Highways
```
L2 <- spatstat.geom::psp(runif(10),runif(10),runif(10),runif(10), window = spatstat.geom::owin())
D2 <- spatstat.core::density.psp(L2, sigma = 0.04)
plot(D2, main = "density(L2)")
plot(L2, add = TRUE, lty = 2)
```
![download](https://user-images.githubusercontent.com/10702814/109396621-7122d080-7900-11eb-8e1f-6272d7ff0805.png)

Surface streets
```
L3 <- spatstat.geom::psp(runif(20),runif(20),runif(20),runif(20), window = spatstat.geom::owin())
D3 <- spatstat.core::density.psp(L3, sigma = 0.02)
plot(D3, main = "density(L3)")
plot(L3, add = TRUE, lty = 3)
```
![download](https://user-images.githubusercontent.com/10702814/109396626-7bdd6580-7900-11eb-8065-c8566d0496a6.png)

All three types combined
```
plot(D1+D2+D3, main = "density(L1) + density(L2) + density(L3)")
plot(L1, add = TRUE, lty = 1)
plot(L2, add = TRUE, lty = 2)
plot(L3, add = TRUE, lty = 3)
```
![download](https://user-images.githubusercontent.com/10702814/109396632-83047380-7900-11eb-9a7e-2d73ba38ea11.png)

Could a potential workaround be to calculate a separate`density.psp` for each type and scale the resulting `im` output?

```
plot(3*D1+2*D2+D3, main = "3*density(L1) + 2*density(L2) + density(L3)")
plot(L1, add = TRUE, lty = 1)
plot(L2, add = TRUE, lty = 2)
plot(L3, add = TRUE, lty = 3)
```
![download](https://user-images.githubusercontent.com/10702814/109396669-b0512180-7900-11eb-930d-8b47c01eb8d1.png)

Thanks and I am open to other suggestions!

**Comment by baddstats** [comment]
The argument `weights` is recognised, and correctly handled, so long as you don't change the value of `method` from its default value `method="FFT"`.   Example:

    library(spatstat.core)
    X <- dirichletEdges(rthin(cells, 0.2))
    D <- density(X)
    DW <- density(X, weights=runif(nobjects(X)))
    plot(solist(X, D, DW))

We haven't documented this in the help file because we haven't implemented `weights` for the other cases `method="C"` and `method="interpreted"`.

 I will take this as a feature request. It will take a while because of the reorganisation of `spatstat`.

**Comment by idblr** [comment]
It feels like I stumbled onto an easter egg! Thanks, @baddstats. The `weights` argument works with the default `method="FFT"` (see below). When using other values for `method`,  the`weights` argument has no effect but also no warning.

Replicating the final (weighted) density plot in my original example above where the geometrical objects of L1 have a weight of 3, L2 has a weight of 2, and L1 has a weight of 1. 
```
set.seed(1234)
library(spatstat.geom)
library(spatstat.core)

L1 <- psp(runif(5), runif(5), runif(5), runif(5), window = owin())
D1 <- density(L1, sigma = 0.06, weights = 3)

L2 <- psp(runif(10), runif(10), runif(10), runif(10), window = owin())
D2 <- density(L2, sigma = 0.04, weights = 2)

L3 <- psp(runif(20), runif(20), runif(20), runif(20), window = owin())
D3 <- density(L3, sigma = 0.02, weights = 1)

plot(D1+D2+D3, main = "density(L1) + density(L2) + density(L3), weighted")
plot(L1, add = TRUE, lty = 1)
plot(L2, add = TRUE, lty = 2)
plot(L3, add = TRUE, lty = 3)
```
![download](https://user-images.githubusercontent.com/10702814/109439997-9bf34e80-79fe-11eb-9442-28b58729fa22.png)

Looks like the `psp` objects could be combined before running the `density.psp()` function with a numeric vector of weights of the same length as geometrical objects, similar to other `density` functions within `spatstat` (as shown in your example). 

Created on 2021-02-28 by the [reprex package](https://reprex.tidyverse.org/) (v1.0.0)

**Comment by baddstats** [comment]
A `weights` argument has been implemented (for all values of `method`) in the current development version `1.65-9`.
