### ISSUE TITLE
Documentation edit for ppm

### ISSUE THREAD

**Issue by rubak** [spatstat/spatstat.core#10]
[This answer](https://stackoverflow.com/a/69044255/3341769) by @baddstats inspired me to look at the `ppm` documentation, and I think we could expand on this section:

https://github.com/spatstat/spatstat.core/blob/0e001499eed4493b19c43f49fc674da2f4e1ae5e/man/ppm.Rd#L148-L159

It is not completely clear that it can be a function of `marks` as well as `x` and `y`.

If we change this we should remember to also do it in `ppm.ppp.Rd`:

https://github.com/spatstat/spatstat.core/blob/0e001499eed4493b19c43f49fc674da2f4e1ae5e/man/ppm.ppp.Rd#L287-L298

**Comment by baddstats** [comment]
Oops, the current documentation is correct, and the code currently refuses to handle a `function(x,y,marks)`

I was _planning_ to allow `function(x,y,marks)` in an update. 

I will implement the update now!

**Comment by rubak** [comment]
Looks like you already fixed this @baddstats, so I will close. Please reopen if I'm wrong.
