### ISSUE TITLE
Corner cases in Edge.Ripley not executing

### ISSUE THREAD

**Issue by Marjolein9** [spatstat/spatstat.core#12]
The ext variable in Edge.Ripley is 1 dim, so the code for the corner doesn't work for me:
#if(any(corner)) ext[corner,] <- ext[corner,] + pi/2

In the code above, I expected 4, not 2 for  method C and for interpretation I got:

Error in ext[corner, ] : incorrect number of dimensions 

library(spatstat)
#created dataframe  with mark in corner (0, 0)
y <- c(0)
x <- c(0)
mark <- c("yes")
df <- data.frame("x" = x, "y" = y, "mark" = mark)
df$mark <- as.factor(df$mark)
W <- owin( c(0, 5), c(0, 5))
all_pp <- as.ppp( df, W = W)
#using interpreted for debugged
edge.Ripley(all_pp, c(1), method = c("interpreted"))
#works but give wrong answer (should be a corner, so return 4)
edge.Ripley(all_pp, c(1))

Further notes:

#https://github.com/spatstat/spatstat.core/blob/master/R/edgeRipley.R
since corner on line 123 is true
if line 123 ran

#if(any(corner))
#ext[corner,] <- ext[corner,] + pi/2

I'd expect ext in the example above to be 3/2 pi (add pi/2 to current ext (pi))
so that weight from below formula = 4,
instead ext remains pi, so weight is two

weight <- 1/(1 - ext/(2 * pi))

#print out without changing code
# 
 "interpreted"
 "ext"
 3.141593
 "corner"
 TRUE
 "ext"
3.141593
"weight"
2

printout with ext[corner] <- ext[corner] + pi/2
"ext"
3.141593
"corner"
 TRUE
"ext"
 4.712389
 "weight"
4

**Comment by baddstats** [comment]
Thank you for reporting this.

The machine on which spatstat is developed has just suffered a hard crash, so I will not be able to investigate this for about 10 days.

**Comment by baddstats** [comment]
In the meantime, try using point patterns with at least 2 points, e.g. `X <- all_pp[c(1,1)]` and then `edge.Ripley(X, c(1,1), method="i")`

**Comment by baddstats** [comment]
@Marjolein9 
What value do you get for `atan2(0,0)` on your machine?

**Comment by baddstats** [comment]
I ran through the calculations in this example by hand, and they would be correct if `atan2(0,0) = 0`. That is the ISO standard behaviour.. But there may be machines which do not obey the standard.

@rubak Could you please edit `edgeRipley.R` so that 

- after line 120, `ext` is converted to a matrix with dimensions `Nr` by `Nc`
- calls to `atan2` in lines 90-97 are replaced by calls to a new local function `ATAN2 <- function(y,x) { ifelse(x ==0 & y == 0, 0, atan2(y,x) }`

and bump the version number?

(This will only affect the interpreted code but will allow us to check whether we have fixed the problem)

Sorry I can't do this myself because my machine has died

**Comment by Marjolein9** [comment]
Thanks for looking into this! And thanks for creating the spatstat package.
For your information, atan2(0,0) returned 0.

If I run your suggestion, adding in print statement, I get the below. I think the problem is the dimensions of ext doesn't work with ext[corner, ]
> X <- all_pp[c(1,1)]
> edge.Ripley(X, c(1,1), method="i")
[1] "cL"
[1] 1.570796 1.570796
[1] "cR"
[1] 0 0
[1] "cU"
[1] 0 0
[1] "cD"
[1] 1.570796 1.570796
[1] "ext"
[1] 3.141593 3.141593
[1] "corner"
[1] TRUE TRUE
Error in ext[corner, ] : incorrect number of dimensions

**Comment by baddstats** [comment]
Yes, of course, but my “suggestion” would make `ext` into a matrix after line 120 so this error would not occur.

**Comment by Marjolein9** [comment]
Yes, of course, thank you!

**Comment by baddstats** [comment]
This is now fixed, in `spatstat.core 2.3-0.023`

The bug in the C code was that the expression `1/4` was evaluated in integer arithmetic, yielding `0` instead of the intended `0.25`.
