### ISSUE TITLE
Error when simulating determinantal point process

### ISSUE THREAD

**Issue by baddstats** [spatstat/spatstat.core#16]
In [this issue posted on spatstat/spatstat](https://github.com/spatstat/spatstat/issues/154#issue-1056357963) @jbrehmer42 says:

Dear `spatstat` developers, when I run the following code

    set.seed(3)
    DPPscale <- 0.1
    DPPvar <- 8.5
    dat <- simulate( dppGauss(lambda = DPPvar, alpha = DPPscale, d = 2), nsim = 100)

then the function `rdppp` throws the error

The dimension differs from the number of columns in index

This happens for the simulation 81/100 in `simulate.detpointprocfamily`. I think the reason is that the matrix in `indexlist[[81]]` created in `simulate.detpointprocfamily` has only one row. When `indexlist` is later passed to the function `rdpp`, then the line

    sampleindex <- as.matrix(index[rbinom(nrow(index), 1, eig)==1, ])

changes the rows and columns of the matrix.

**Comment by baddstats** [comment]
Thank you for telling us.

I can reproduce the error.

A fix will be uploaded shortly.

**Comment by baddstats** [comment]
The same error can be demonstrated with `set.seed(256)` and `nsim=1`.

**Comment by baddstats** [comment]
It appears to be the usual `drop=FALSE` bug. 

I am running an exhaustive test.

**Comment by baddstats** [comment]
Bug is fixed in `spatstat.core 2.3-1.015`.

**Comment by baddstats** [comment]
@rubak is this fix ok?

**Comment by rubak** [comment]
Yes @baddstats your `drop = FALSE` fix is spot on as far as I can tell. Thanks for fixing it.
