### ISSUE TITLE
Bug in visual debugger of rmh

### ISSUE THREAD

**Issue by baddstats** [spatstat/spatstat.core#17]
Redirected issue from https://github.com/spatstat/spatstat/issues/155#issue-1088055003 raised by @dschuhmacher

It appears the visual debugger in the function `rmh` does not display accepted births and deaths correctly, i.e. accepted births are not added to the displayed point pattern in the next step and accepted deaths are not deleted from it. For moves everything seems to work fine. The issue happens for me both on `quartz`- and `x11`-devices.

Minimal reproducible example:

     mod <- list(cif="strauss", par=list(beta=200, gamma=0.1, r=0.05), w=c(0,1,0,1))
     cont <- list(p=0, q=0.5)
     set.seed(44)
     xi <- rmh(model=mod, start=list(n.start=1), control=cont, snoop = TRUE)

Also, if we start with an empty point pattern (`n.start=0`), the visual debugger auto-exits after a single step. I presume it exits whenever it reaches the empty point pattern after the initial step.

**Comment by baddstats** [comment]
Bug confirmed and localised

**Comment by baddstats** [comment]
I think the bug is fixed in `spatstat.core 2.3-2.004`

**Comment by baddstats** [comment]
Please try it out

**Comment by dschuhmacher** [comment]
I tried out several scenarios and it works fine now. Thanks!
