### ISSUE TITLE
Corner case for Kest

### ISSUE THREAD

**Issue by Marjolein9** [spatstat/spatstat.core#21]
I'm not getting the answer I would expect from Kest when one of the points is a corner case. I'd expect the Ripley value for a corner case to nearly be value for a point very close to the corner. May just be misunderstanding, which has happened before :)
The outcome for a corner point (0,0) is [1] 0 8 vs [1]  0.00000 11.99995 for (.00001, 0)

`library(spatstat.core)
packageVersion("spatstat.core")

W <- owin( c(0, 2), c(0, 2))

### Kest with no corner cases (.00001 vs 0)
df <- data.frame(x = c( 0, 0),
                 y = c(0.00001, 1))

all_pp <- as.ppp( df, W = W)

univariate = Kest(all_pp, r = c(0,1.2500), 
                  correction=c("Ripley"))
univariate$iso
### outcome [1]  0.00000 11.99995

univariate_result = sqrt(univariate$iso/pi) - univariate$r
univariate_result

### Kest with corner case (0 rather than .00001)
df <- data.frame(x = c( 0, 0),
                 y = c(0, 1))

all_pp <- as.ppp( df, W = W)

univariate2 = Kest(all_pp, r = c(0,1.2500), 
                  correction=c("Ripley"))

### but looks like it isn't weighing the corner correctly
univariate2$iso

### outcome [1] 0 8

univariate2_result = sqrt(univariate2$iso/pi) - univariate2$r
univariate2_result

### edge weight is working as expected (below) so not sure where error is coming from

x <- c(0, 1)
y <- c(0, 0)
df <- data.frame("x" = x, "y" = y)
W <- owin( c(0, 2), c(0, 2))
all_pp <- as.ppp( df, W = W)
#(should be a corner, so return 4)
edge.Ripley(all_pp, c(1, 1))`

**Comment by baddstats** [comment]
Please note that `spatstat.core` is now obsolete. It has been split into two packages, `spatstat.explore` and `spatstat.model`, which are now on CRAN.

The problem that you describe is still occurring in the latest version of `spatstat.explore` (3.0-3). The correct answer is 12, not 8. I will investigate.

**Comment by baddstats** [comment]
This was a bug in C code. It has now been fixed in `spatstat.explore 3.0-4`.
