### ISSUE TITLE
Error: object 'integral' not found whilst loading namespace 'spatstat.core'

### ISSUE THREAD

**Issue by mailmrcai** [spatstat/spatstat.core#22]
Error: object 'integral' not found whilst loading namespace 'spatstat.core'

**Comment by baddstats** [comment]
The package `spatstat.core` no longer exists. It was removed 4 years ago, and replaced by two packages, `spatstat.explore` and `spatstat.model`. Please update your installation of `spatstat`. 

If you are a package developer, you will need to replace the dependence on `spatstat.core` by dependence on `spatstat.explore`,  `spatstat.model` and `spatstat.univar`.

The function `integral` is now in package `spatstat.univar`.

**Comment by LONGsci** [comment]
You can download the corresponding version of the source code from the website https://cran.r-project.org/src/contrib/Archive/Seurat/. I used Seurat_4.1.0.tar.gz. Then, unzip it and use R Studio - Edit - Find in Files to locate all instances of “spatstat.core” and replace them with “spatstat.explore”. After that, use system(“R CMD build .”) to re-compress it. You can then install it using the new package!

**Comment by rubak** [comment]
The above mentioned hack to modify the source code of a package like `Seurat` is not recommended and should be avoided if possible. The newest version of `Seurat` works perfectly fine with the `spatstat` family of packages without any hack. Of course there may be very special circumstances where a specific old version of a package is needed, and then the trick described by @LONGsci may be helpful, but I will stress that it is usually not recommended.
