### ISSUE TITLE
Error in `Kest()` when `var.approx = TRUE`

### ISSUE THREAD

**Issue by rubak** [spatstat/spatstat.core#9]
Together with @biscio I encountered an uninformative error when running something like this:

```r
library(spatstat.core)
Kest(cells, correction = "trans", var.approx = TRUE)
```

It comes from unconditionally assuming isotropic correction is chosen when `var.approx = TRUE` when we refer to `"iso"` in `bind.fv` here:
https://github.com/spatstat/spatstat.core/blob/4195d6e1c863fd214be1033bf94dc4473bb3c54b/R/Kest.R#L329-L334

I guess the approximation is developed for isotropic correction so we need to decide whether to give an error when this correction is not chosen or calculate the approximation anyway.

**Comment by baddstats** [comment]
Thanks for spotting this. The variance approximation is for the isotropic correction. It would be technically possible, but probably never makes sense, to compute this variance approximation without computing the isotropic corrected estimate of K. So I will just put in a line to ignore var.approx=TRUE if the isotropic correction is not selected. And a warning() or warn.once()
